import mongoose, { Document, Schema, Types } from 'mongoose';

export interface IAction extends Document {
    clientActionId: string; // A UUID generated by the frontend to prevent duplicate processing
    userId: Types.ObjectId; // Who performed the action
    taskId?: Types.ObjectId; // Which task was affected (optional for creations)
    actionType: 'CREATE_TASK' | 'UPDATE_TASK' | 'MOVE_TASK' | 'DELETE_TASK';
    payload: any; // Flexible field to store the changes (e.g., { status: 'Done', order: 2 })
    timestamp: Date; // When the client ACTUALLY made the change offline
    status: 'PENDING' | 'PROCESSED' | 'FAILED'; // Tracks sync state
    conflictResolved: boolean; // Flag if the server had to merge conflicting changes
    createdAt: Date;
    updatedAt: Date;
}

const actionSchema = new Schema<IAction>(
    {
        clientActionId: {
            type: String,
            required: true,
            unique: true, // Crucial: Prevents a spotty connection from applying the same offline move twice
        },
        userId: {
            type: Schema.Types.ObjectId,
            ref: 'User',
            required: true,
        },
        taskId: {
            type: Schema.Types.ObjectId,
            ref: 'Task',
            // Not strictly required because a CREATE_TASK action might not have a Mongo ID yet
        },
        actionType: {
            type: String,
            enum: ['CREATE_TASK', 'UPDATE_TASK', 'MOVE_TASK', 'DELETE_TASK'],
            required: true,
        },
        payload: {
            type: Schema.Types.Mixed, // Allows us to store any JSON object of changes
            required: true,
        },
        timestamp: {
            type: Date,
            required: true, // The exact time the user clicked the button while offline
        },
        status: {
            type: String,
            enum: ['PENDING', 'PROCESSED', 'FAILED'],
            default: 'PENDING',
        },
        conflictResolved: {
            type: Boolean,
            default: false,
        },
    },
    { timestamps: true }
);

// Index for fast querying when syncing a specific user's queue
actionSchema.index({ userId: 1, status: 1 });
// Index to sort by oldest actions first to process them in the exact order they happened
actionSchema.index({ timestamp: 1 });

export const Action = mongoose.model<IAction>('Action', actionSchema);